version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - flovogt
  versioning-strategy: increase
  commit-message:
    prefix: "[DEPENDENCY]"
    prefix-development: "[INTERNAL]"