name: Bug Report
description: Report an issue with OpenUI5
body:
  - type: markdown
    attributes:
      value: |
        |
        Note: Hey there 👋 Please have a look at our [contributing guidelines](https://github.com/SAP/openui5/blob/main/CONTRIBUTING.md#report-bugs) on reporting issues.
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Tell us, what did you expect to happen.
      placeholder: Tell us, what did you expect to happen.
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: What is the current behavior?
      description: Tell us what you see.
      placeholder: Tell us what you see.
    validations:
      required: true  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How we can reproduce the issue?
      description: Please provide detailed steps on how we can reproduce your issue.
      placeholder: Provide a minimal example via an URL (if possible) or consider forking our sample app to reproduce it https://github.com/SAP/openui5-sample-app
    validations:
      required: true
  - type: input
    id: version-OpenUI5
    attributes:
      label: OpenUI5 version
      description: The exact version of OpenUI5
      placeholder: e.g. 1.120.25
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: The used operating system with version
      placeholder: e.g. macOS 15.3.2
  - type: input
    id: browsers
    attributes:
      label: Browser
      description: The used browser with version
      placeholder: e.g. Mozilla Firefox 136.0.1
  - type: textarea
    id: logs
    attributes:
      label: Log Output / Stack Trace
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
