name: Feature Request
description: Request a new feature for OpenUI5
body:
  - type: markdown
    attributes:
      value: | 
        Please have a look at our [contributing guidelines](https://github.com/SAP/openui5/blob/main/CONTRIBUTING.md#report-features) on requesting features to be added.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem, e.g. "I'm always frustrated when {...}.
      placeholder: A clear and concise description of the problem, e.g. "I'm always frustrated when {...}.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: How a possible solution would look like?
      description: A clear and concise description of what you want to happen.
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternative-solution
    attributes:
      label: Are there alternative approaches?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Is there any further information you wanna share?
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots about the feature request here.
